uname -a #(Check which system is installed)
which gpg #(Check the installation)
gpg --version #(Check the GPG version)
gpg --full-generate-key #(Generate a key pair)
gpg --list-keys #(Lists the keyring)
gpg --armor --export #(This command exports the public key)
gpg --list-secret-keys --keyid-format=long #( This command lists the private keys)
# hash copied from the private key A13BBAAB40C5844C
gpg --armor --export-secret-keys A13BBAAB40C5844C  #(this command exports our private key)
gpg --import keyla_llave.publica.asc #(This command allows us to import my friend's public key into our codespace)
echo "que bueno que somos compañeros" > doc_no_cifrado.txt #(This creates a message that will be sent to the document we name, which in this case is “doc_no_cifrado.txt”")
cat doc_no_crifrado.txt # (This command helps us verify that the file has been created)
gpg --output doc_cifrado.txt --encrypt --recipient 602E18698BE064A4DA50D12408F019E40AC3E0AE doc_no_cifrado.txt #(This command encrypts the file we entered earlier using our partner's hash and sends it to them )
cat doc_cifrado.txt #(This command helps us check what's inside the file)
gpg --decrypt keyla_doc_cifrado.txt #(This command helps us decrypt my friend's message)
gpg --output doc_no_cifrado_firmado.txt --clearsign doc_no_cifrado.txt #(This command allows us to sign the document we created earlier)
cat doc_no_cifrado_firmado.txt #(This command helps us check the signed document)
gpg --verify keyla_doc_no_cifrado_firmado.txt #(This command allows us to verify the signature of the document of friend we signed earlier)
# The key used to sign my friend's unencrypted file: 602E18698BE064A4DA50D12408F019E40AC3E0AE
gpg --edit-key 602E18698BE064A4DA50D12408F019E40AC3E0AE #(This command allows us to edit the key of our friend and giving a vote of confidence. In this case, we choose level 4 because I know this person in person, I know who they are, and I have a certain level of trust in them, just as I do with my classmates.)
gpg --sign-key 08F019E40AC3E0AE #(This command allows us to sign the key of our friend)
gpg --verify keyla_doc_no_cifrado_firmado.txt #(This command allows us to verify the signature of the document of friend we signed earlier)
gpg --output doc_no_cifrado_firmado_binario.txt --sign doc_no_cifrado.txt #(This command allows us to sign the document we created earlier in binary format)
gpg --verify keyla_doc_no_cifrado_firmado_binario.txt #(This command allows us to verify the signature of the document of friend we signed earlier in binary format)
gpg --output firma_separada_doc_no_cifrado.sig --detach-sign doc_no_cifrado.txt #(This command allows us to create a separate signature for the document we created earlier)
gpg --verify keyla_firma_separada_doc_no_cifrado.sig keyla_doc_no_cifrado_firmado.txt #(This command allows us to verify the separate signature of the document of friend we signed earlier)
gpg --output doc_cifrado_y_firmado.txt --encrypt --sign --recipient 602E18698BE064A4DA50D12408F019E40AC3E0AE doc_no_cifrado.txt #(This command allows us to encrypt and sign the document we created earlier and send it to our friend)
gpg --output doc_firmado_y_firmado_descifrado_y_validado.txt --decrypt keyla_doc_cifrado_y_firmado.txt #(This command allows us to decrypt the document that our friend sent us and verify the signature at the same time)
cat doc_firmado_y_firmado_descifrado_y_validado.txt #(This command helps us check the content of the document that our friend sent us)
